project/books/models.py
from project import db,app

class Books(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    bookname = db.Column(db.String(30))
    author = db.Column(db.String(15))
    publishdate = db.Column(db.String(10))
    typeofloan = db.Column(db.Integer)
    loans = db.relationship('Loans', backref='books')

    def __init__(self,bookname,author,publishdate,typeofloan):
        self.bookname = bookname
        self.author = author
        self.publishdate = publishdate
        self.typeofloan = typeofloan
        
with app.app_context():
    db.create_all()

project/books/__init__.py
# this file allows us to import components into main app.py file
# python needs this for it to understand that this is a module that it can import

project/books/views.py
from flask import render_template, redirect, Blueprint, request
from project import db
from project.books.models import Books

books = Blueprint('books', __name__, template_folder='templates', url_prefix = '/books')

'''Function that shows books based on index given in the url's endpoint
or shows all books if no index was given.
Default is set to show all books.'''
@books.route("/", methods=["GET"])
@books.route("/<ind>")
def show_book_list(ind=-1):
    if int(ind)==-1:
        return render_template('all_books.html', books = Books.query.all())
    if int(ind) > -1:
        single_book=Books.query.get(int(ind))
        return render_template('books.html', single_book=single_book)

'''Function made to search a specific book based 
on the index given in the url's endpoint from the function above.'''
@books.route("/book_search", methods=['POST'])
def books_name():
    name = request.form['bookname']
    # If the book's name from the html <input> tag matches a name from the database it redirects you to said database id in the url's endpoint.
    book = Books.query.filter(Books.bookname==name).first()
    # If book does not exist you get redirected to the same page that shows all books.
    if book is None:
        return redirect('/books')
    return redirect(f"{book.id}") 

# Function made to render a page where a user can add a new book to the library.
@books.route("/add_book")
def new_book_page():
    return render_template('add_book.html')

# Function made to add a new book from the page created by previous function.
@books.route("/", methods=['POST'])
def add_books():
    # Making a form that connects to the <form> html tag for user input.
    request_data = request.form
    bookname= request_data["bookname"]
    author = request_data["author"]
    publishdate = request_data["publishdate"]
    # Type of loan connects to the return date of a book.
    typeofloan = request_data["typeofloan"]
    new_book = Books(bookname,author,publishdate,typeofloan)
    db.session.add(new_book)
    db.session.commit()
    return redirect('/books')

# Function made to delete a book from the databse based on the index (id) of the book.
@books.route("/books_del", methods=['GET'])
@books.route("/books_del/<ind>")
def delete_book(ind):
    book = Books.query.get(ind)
    # If the book does not exist return to the endpoint that shows all books.
    if book is None:
        return render_template('all_books.html', books=Books.query.all())
    try:
        db.session.delete(book)
        db.session.commit()
    except:
        return render_template('all_books.html', books=Books.query.all())
    return render_template('all_books.html', books=Books.query.all())
    # After function is done running it will render the page that shows all books.

project/books/templates/add_book.html
{% extends "layout.html" %}
{% block title %}Index{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<!-- Form that gets information from user's input and sends it to the server's database -->
<form action="{{ url_for('books.add_books') }}" method="post">
    <label for="bookname">Book Name: </label>
    <input type="text" name="bookname" placeholder="Enter Book Name" maxlength="30" required>
    <hr>
    <label for="author">Author Name: </label>
    <input type="text" name="author" placeholder="Enter Author Name" maxlength="15" required>
    <hr>
    <label for="publishdate">Publish Date: </label>
    <input type="date" name="publishdate" placeholder="Enter Publish Date" required>
    <hr>
    <label for="typeofloan">Type of loan: </label>
    <input type="number" name="typeofloan" placeholder="Author Name" min="1" max="3" required>
    <hr>
    <button type="submit" class="btn btn-success">Submit new book</button>
</form>
{% endblock %}

project/books/templates/all_books.html
{% extends "layout.html" %}
{% block title %}Index{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<div class="container">
  <div class="row align-items-start">
    <div class="col"></div>
    <div class="col">
      <!-- Form that gets information for the book's search bar and checks with the server's database if exists.
      and if it exists it shows on a different page the outcome of the search -->
      <form class="form-inline" action="{{ url_for('books.books_name') }}" method="POST">
        <div class="input-group">
          <input type="text" class="form-control" name="bookname" placeholder="Search a book">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </div>
      </form>
    </div>
    <div class="col text-right">
      <a class="btn btn-success" href="/books/add_book" role="button">Add a new book!</a>
    </div>
  </div>
</div>
<!-- Shows all books in the library's database -->
<h1>All Books</h1>
<div class="row row-cols-1 row-cols-md-3 g-4">
  {%- for book in books %}
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{book.bookname}}</h5>
        <p class="card-text">
          Book ID: {{book.id}}
          <br>
          Book author: {{book.author}}
          <br>
          Loan type: {{book.typeofloan}}
        </p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Book publish date: {{book.publishdate}}</small>
      </div>
      <div>
        <a href="/books/books_del/{{book.id}}">
          <button class="btn btn-danger">Delete</button>
        </a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

project/books/templates/books.html
{% extends "layout.html" %}
{% block title %}Books{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<h1 class="h1">Book found!</h1>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <!-- Jinja to show a single client after using the search form if it found a client. -->
    <h5 class="card-title">Book name: {{single_book.bookname}}</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Book ID: {{single_book.id}}</li>
    <li class="list-group-item">Book's Author: {{single_book.author}}</li>
    <li class="list-group-item">Book's Publishdate {{single_book.publishdate}}</li>
    <li class="list-group-item">Type of possible loan: {{single_book.typeofloan}}</li>
  </ul>
  <div class="card-body">
    <a href="/books/books_del/{{single_book.id}}">
      <button class="btn btn-danger">Delete</button>
    </a> 
    <a href="/books" class="card-link">
      <button class="btn btn-primary">Go back to all books</button>
    </a>
  </div>
</div>
{% endblock %}