project/clients/models.py
from project import db,app

class Clients(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    clientname = db.Column(db.String(15))
    age = db.Column(db.Integer)
    city = db.Column(db.String(15))
    loans = db.relationship('Loans', backref='clients')

    def __init__(self,clientname,age,city):
        self.clientname = clientname
        self.age = age
        self.city = city

with app.app_context():
    db.create_all()

project/clients/__init__.py
# this file allows us to import components into main app.py file
# python needs this for it to understand that this is a module that it can import

project/clients/views.py
from flask import render_template, redirect, Blueprint, request
from project import db
from project.clients.models import Clients



client = Blueprint('client', __name__, template_folder='templates',url_prefix='/client')

'''Function that shows clients based on name given in the url's endpoint
or shows all clients if no name was given.
Default is set to show all clients.'''
@client.route("/", methods=['GET'])
@client.route("/<name>")
def client_list(name=""):
    if name == "":
        clients = Clients.query.all()
        return render_template('all_clients.html', clients=clients)
    if name != "":
        single_client = Clients.query.filter(Clients.clientname==name).first()
        return render_template('clients.html', single_client=single_client)

'''Function made to search a specific client based 
on the name given in the url's endpoint from the function above.'''
@client.route("/client_search", methods=['POST'])
def client_name():
    name = request.form['clientname']
    # If the client's name from the html <input> tag matches a name from the database it redirects you to said database client name in the url's endpoint.
    client = Clients.query.filter(Clients.clientname==name).first()
    # If client does not exist you get redirected to the same page that shows all clients.
    if client is None:
        return redirect('/client')
    return redirect(f"{client.clientname}") 

# Function made to render a page where a user can add a new client to the library.
@client.route("/add_client")
def add_client_page():
    return render_template("add_client.html")

# Function made to add a new client from the page created by previous function.
@client.route("/", methods=['POST','GET'])
def add_client():
    if request.method == 'POST':
        # Making a form that connects to the <form> html tag for user input.
        request_data = request.form
        clientname = request_data["clientname"]
        age = request_data["age"]
        city = request_data["city"]
        new_customer = Clients(clientname,age,city)
        db.session.add(new_customer)
        db.session.commit()
        return redirect('/client')

# Function made to delete a client from the database based on the index (id) of the client.
@client.route("/client_del", methods=['GET','DELETE'])
@client.route("/client_del/<ind>")
def client_del(ind):
    client = Clients.query.get(int(ind))
    # If the client does not exist return to the endpoint that shows all clients.
    if client is None:
        return render_template('all_clients.html', clients=Clients.query.all())
    try:
        db.session.delete(client)
        db.session.commit()
    except:
        return render_template('all_clients.html', clients=Clients.query.all())
    return render_template('all_clients.html', clients=Clients.query.all())
    # After function is done running it will render the page that shows all clients.

project/clients/templates/add_client.html
{% extends "layout.html" %}
{% block title %}Index{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}


{% block content %}
<!-- Form that gets information from user's input and sends it to the server's database -->
<form action="{{ url_for('client.add_client') }}" method="POST">
    <label for="clientname">Client Name: </label>
    <input type="text" name="clientname" placeholder="Enter Client Name" maxlength="15" required>
    <hr>
    <label for="age">Age: </label>
    <input type="number" name="age" placeholder="Enter your age" min="1" max="120" required>
    <hr>
    <label for="city">City: </label>
    <input type="text" name="city" placeholder="Enter City" maxlength="15" required>
    <hr>
    <button type="submit" class="btn btn-success">Submit new book</button>
</form>
  
{% endblock %}

project/clients/templates/all_clients.html
{% extends "layout.html" %}
{% block title %}Index{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<div class="container">
    <div class="row align-items-start">
        <div class="col"></div>
        <div class="col">
            <!-- Form that gets information for the client's search bar and checks with the server's database if exists.
            and if it exists it shows on a different page the outcome of the search -->
            <form class="form-inline" action="{{ url_for('client.client_name') }}" method="POST">
                <div class="input-group">
                    <input type="text" class="form-control" name="clientname" placeholder="Search a client">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </div>
            </form>
        </div>
        <div class="col text-right">
            <a class="btn btn-success" href="/client/add_client" role="button">Add a new client!</a>
        </div>
    </div>
</div>
<h1>All Clients</h1>
<div class="row row-cols-1 row-cols-md-3 g-4">
    <!-- Jinja loop to show all clients and their information. -->
    {%- for client in clients %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{client.clientname}}</h5>
                <p class="card-text">
                    Age: {{client.age}}
                    <br>
                    City: {{client.city}}
                </p>
            </div>
            <div class="card-footer">
                <small class="text-muted">Client ID: {{client.id}}</small>
            </div>
            <div>
                <a href="/client/client_del/{{client.id}}">
                    <button class="btn btn-danger">Delete</button>
                </a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

project/clients/templates/clients.html
{% extends "layout.html" %}
{% block title %}Index{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<h1 class="h1">Client found!</h1>
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <!-- Jinja to show a single client after using the search form if it found a client. -->
    <h5 class="card-title">Client name: {{single_client.clientname}}</h5>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Client ID: {{single_client.id}}</li>
    <li class="list-group-item">Client's Age {{single_client.age}}</li>
    <li class="list-group-item">Client's City: {{single_client.city}}</li>
  </ul>
  <div class="card-body">
    <a href="/client/client_del/{{single_client.id}}">
      <button class="btn btn-danger">Delete</button>
    </a> 
    <a href="/client" class="card-link">
      <button class="btn btn-primary">Go back to all clients!</button>
    </a>
  </div>
</div>
{% endblock %}