project/loans/models.py
from project import db,app

class Loans(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    customer_id = db.Column(db.Integer, db.ForeignKey('clients.id'))
    book_id = db.Column(db.Integer, db.ForeignKey('books.id'))
    loandate = db.Column(db.Date)
    returndate = db.Column(db.Date)
    returned = db.Column(db.Boolean, nullable=False)



    def __init__(self,customer_id,book_id,loandate,returndate):
        self.customer_id = customer_id
        self.book_id = book_id
        self.loandate = loandate
        self.returndate = returndate
        self.returned = False

with app.app_context():
    db.create_all()

project/loans/views.py
from flask import Blueprint, render_template, request, redirect, flash
from project import db
from datetime import datetime, timedelta
from project.clients.models import Clients
from project.loans.models import Loans
from project.books.models import Books

loans = Blueprint('loans', __name__, template_folder = 'templates', url_prefix = '/loans')

# Function made to render a page showing all loans.
@loans.route("/", methods=['GET'])
def loan_list():
    loans = Loans.query.all()
    return render_template('loans.html', loans=loans)

# Function made to render a page where a user can create a new loan.
@loans.route("/add_loan")
def new_loan_page():
    books = Books.query.all()
    clients = Clients.query.all()
    return render_template('add_loan.html', books = books, clients = clients)

# Function made to create a new loan from the page created by previous function.
@loans.route("/", methods=['POST'])
def loan():
    # Making a form that connects to the <form> html tag for user input.
    request_data = request.form
    customer_id = int(request_data["customer_id"])
    book_id = int(request_data["book_id"])
    # Sets automatic date upon creation of a loan (always the current date).
    loandate = datetime.today()
    if Books.query.get(book_id):
        if Clients.query.get(customer_id):
            for book in Books.query.filter(Books.id):
                if book_id == book.id:
                    # Setting automatic return date based on the type of loan of each book.
                    if book.typeofloan == 1: returndate = loandate + timedelta(days=10)
                    elif book.typeofloan == 2: returndate = loandate + timedelta(days=5)
                    elif book.typeofloan == 3: returndate = loandate + timedelta(days=2)
            new_loan = Loans(customer_id,book_id,loandate,returndate)   
            db.session.add(new_loan)
            db.session.commit()
            flash("New loan has been created.")
        # If client was not found in the Database it flashes on the site with the message.
        else: flash("Client not found.")
    # If book was not found Database it flashes on the site with the message.
    else: flash("Book not found.")
    return redirect("/loans")
    
# Function made to show all late loans that the return date of them has passed.
@loans.route('/late_loans', methods=['GET'])
def show_late_loans():
    late_loans = []
    active_loans = Loans.query.filter_by(returned= False)
    for loan in active_loans:
            # This line checks if the returndate of a specific loan is smaller than today's date.
            if loan.returndate < datetime.today().date():
                late_loans.append(loan)
    return render_template ("late_loans.html", late_loans=late_loans)

# Function made to return a book from the database based on the index (id) of the loan.
@loans.route("/loans_del", methods=['GET','DELETE'])
@loans.route("/loans_del/<ind>")
def return_loan(ind):
    loan = Loans.query.get(int(ind))
    # If the loan does not exist return to the endpoint that shows all loans.
    if loan is None:
        return render_template('loans.html', loans=Loans.query.all())
    try:
        db.session.delete(loan)
        db.session.commit()
    except:
        return render_template('loans.html', loans=Loans.query.all())
    return render_template('loans.html', loans=Loans.query.all())
    # After function is done running it will render the page that shows all loans.

project/loans/templates/add_loan.html
{% extends "layout.html" %}
{% block title %}Index{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <!-- Form that gets information from user's input and sends it to the server's database -->
            <form action="{{ url_for('loans.loan') }}" method="POST">
                <label for="customer_id">Client ID: </label>
                <input type="number" name="customer_id" placeholder="Enter Client ID" required>
                <hr>
                <label for="book_id">Book ID: </label>
                <input type="number" name="book_id" placeholder="Enter Book ID" required>
                <hr>
                <button type="submit" class="btn btn-success">Submit new book</button>
            </form>

        </div>
        <!-- Table that shows all Books and all clients in the library using Jinja to make it easier
        to write them on the form. -->
        <div class="col">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Book ID</th>
                        <th scope="col">Book name</th>
                    </tr>
                </thead>
                <tbody>
                    {% for book in books %}
                    <tr>
                        <td>{{ book.id }}</td>
                        <td>{{ book.bookname }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Client ID</th>
                        <th scope="col">Client name</th>
                    </tr>
                </thead>
                <tbody>                        
                    {% for client in clients %}
                    <tr>
                        <td>{{ client.id }}</td>
                        <td>{{ client.clientname }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
</div>
{% endblock %}

project/loans/templates/late_loans.html
{% extends "layout.html" %}
{% block title %}Index{% endblock %}
{% block head %}
{{ super() }}
{% endblock %}

{% block content %}
<h1 class="h1">Late loans here... :(</h1>
<div class="row row-cols-1 row-cols-md-3 g-4">
    <!-- jinja loop to show all late loans -->
    {%- for loan in late_loans %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Book name: {{loan.books.bookname}}</h5>
                <p class="card-text">
                    Client ID: {{ loan.clients.id }} <br>
                    Client Name: {{ loan.clients.clientname }} <br>
                    Client supposed returndate: <br>{{ loan.returndate }}
                </p>
            </div>
            <div class="card-footer">
                <small class="text-muted">
                    <a href="/loans/loans_del/{{loan.id}}">
                        <button class="btn btn-danger">Return Late Loan</button>
                    </a>
                </small>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

project/loans/templates/loans.html
{% extends "layout.html" %}
{% block title %}Index{% endblock %}
{% block head %}
{{ super() }}
<style type="text/css">
  .important {
    color: #336699;
  }
</style>
{% endblock %}

{% block content %}
{% for message in get_flashed_messages() %}
<h2 class="opacity-75 bg-danger mx-auto" style="width: 375px;">{{ message }}</h2>
{% endfor %}
<div class="container">
  <div class="row align-items-start">
    <div class="col"></div>
    <div class="col">
      <a class="btn btn-primary" href="/loans/late_loans" role="button">Show late loans</a>
    </div>
    <div class="col text-right">
      <a class="btn btn-success" href="/loans/add_loan" role="button">Add a new loan!</a>
    </div>
  </div>
</div>
<h1>All Loans</h1>
<div class="row row-cols-1 row-cols-md-3 g-4">
  {%- for loan in loans %}
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{loan.books.bookname}}</h5>
        <p class="card-text">
          Loaned by: {{loan.clients.clientname }} <br>
          Loan date: {{loan.loandate}}
          <br>
          Return date: {{loan.returndate}}
        </p>
      </div>
      <div class="card-footer">
        <small class="text-muted">Loan ID: {{loan.id}}</small>
      </div>
      <div>
        <a href="/loans/loans_del/{{loan.id}}">
          <button class="btn btn-danger">Delete</button>
        </a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}